"""Validate PUBLIC Firebase client identifiers and write Dart build defines.

Never pass a Firebase service-account JSON here. That belongs only in Render.
"""
import argparse
import json
import os
from pathlib import Path
import re
import xml.etree.ElementTree as ET

ALLOWED = {'PUSH_ENABLED', 'FIREBASE_PROJECT_ID', 'FIREBASE_MESSAGING_SENDER_ID',
           'FIREBASE_ANDROID_APP_ID', 'FIREBASE_ANDROID_API_KEY',
           'FIREBASE_IOS_APP_ID', 'FIREBASE_IOS_API_KEY', 'FIREBASE_IOS_BUNDLE_ID'}

def prepare(raw):
    if not raw.strip():
        return {'PUSH_ENABLED': False}
    value = json.loads(raw)
    if not isinstance(value, dict) or set(value) - ALLOWED:
        raise ValueError('Only public Firebase client identifiers are allowed. Never use a service-account key here.')
    if value.get('PUSH_ENABLED') is False:
        return {'PUSH_ENABLED': False}
    required = {'FIREBASE_PROJECT_ID', 'FIREBASE_MESSAGING_SENDER_ID',
                'FIREBASE_ANDROID_APP_ID', 'FIREBASE_ANDROID_API_KEY'}
    if any(not isinstance(value.get(k), str) or not value[k].strip() for k in required):
        raise ValueError('Complete all four Android Firebase client fields.')
    if not re.fullmatch(r'[a-z][a-z0-9-]{4,62}', value['FIREBASE_PROJECT_ID']):
        raise ValueError('Invalid Firebase project ID.')
    if not value['FIREBASE_MESSAGING_SENDER_ID'].isdigit():
        raise ValueError('Sender ID must be the numeric Firebase project number.')
    if not re.fullmatch(r'1:[0-9]+:android:[a-fA-F0-9]+', value['FIREBASE_ANDROID_APP_ID']):
        raise ValueError('Use the Android Firebase app ID, not the package name.')
    if value['FIREBASE_ANDROID_APP_ID'].split(':')[1] != value['FIREBASE_MESSAGING_SENDER_ID']:
        raise ValueError('App ID and sender ID must belong to the same project.')
    for key, item in value.items():
        if key != 'PUSH_ENABLED' and (not isinstance(item, str) or len(item) > 256 or '\n' in item):
            raise ValueError('Invalid Firebase client field.')
    return {**value, 'PUSH_ENABLED': True}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', required=True)
    parser.add_argument('--config')
    parser.add_argument('--android-root')
    args = parser.parse_args()
    raw = Path(args.config).read_text(encoding='utf-8-sig') if args.config else os.getenv('SENDOH_FIREBASE_CONFIG', '')
    try:
        value = prepare(raw)
    except (ValueError, TypeError):
        raise SystemExit('Invalid push build configuration. Use the public client JSON described in docs/NOTIFICATIONS_UPDATE.md.')
    destination = Path(args.output)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(value), encoding='utf-8')
    if args.android_root:
        android = Path(args.android_root)
        if not (android / 'app/src/main/AndroidManifest.xml').exists():
            raise SystemExit('Generate the Android project before preparing push configuration.')
        resources = android / 'app/src/main/res/values/sendoh_firebase.xml'
        marker = '<!-- Generated by Sendoh prepare_push_build.py -->'
        if resources.exists() and marker not in resources.read_text():
            raise SystemExit('Existing custom sendoh_firebase.xml needs manual review.')
        if value['PUSH_ENABLED']:
            if (android / 'app/google-services.json').exists():
                raise SystemExit('Existing google-services.json detected. Review native Firebase configuration before using this build helper.')
            # FirebaseInitProvider needs native options even when Flutter is not
            # running, so terminated-app Android notifications work as well.
            root = ET.Element('resources')
            fields = {'google_app_id': 'FIREBASE_ANDROID_APP_ID',
                'google_api_key': 'FIREBASE_ANDROID_API_KEY',
                'gcm_defaultSenderId': 'FIREBASE_MESSAGING_SENDER_ID',
                'project_id': 'FIREBASE_PROJECT_ID'}
            for name, source in fields.items():
                ET.SubElement(root, 'string', {'name':name, 'translatable':'false'}).text = value[source]
            resources.parent.mkdir(parents=True, exist_ok=True)
            resources.write_text(marker + '\n' + ET.tostring(root, encoding='unicode') + '\n', encoding='utf-8')
        elif resources.exists():
            resources.unlink()
    print('Push build configuration: enabled' if value['PUSH_ENABLED'] else 'Push build configuration: inbox only')

if __name__ == '__main__':
    main()
